<script setup lang="ts">
const router = useRouter()
const page = ref(1)
const pageSize = 20
const search = ref('')
const { data, refresh } = await useFetch('/api/iam/users-full', {
  query: computed(() => ({ page: page.value, pageSize, search: search.value }))
})

// Column visibility
const showColumnSelector = ref(false)
const columns = ref([
  { key: 'username', label: 'User name', visible: true, required: true },
  { key: 'groups', label: 'Groups', visible: true },
  { key: 'accessKeyAge', label: 'Access key age', visible: true },
  { key: 'passwordAge', label: 'Password age', visible: true },
  { key: 'mfa', label: 'MFA', visible: true },
  { key: 'lastActivity', label: 'Last activity', visible: true },
  { key: 'consoleLastSignIn', label: 'Console last sign-in', visible: true },
  { key: 'accessKeyLastUsed', label: 'Access key last used', visible: true },
])
const visibleColumns = computed(() => columns.value.filter(c => c.visible))

// Create user wizard state
const showCreateWizard = ref(false)
const createStep = ref(1)
const createSuccess = ref(false)
const createdUsername = ref('')
const createdUserId = ref('')
const createForm = ref({
  username: '',
  consoleAccess: false,
  passwordType: 'autogenerated' as 'autogenerated' | 'custom',
  customPassword: '',
  requirePasswordChange: true,
  permissionMode: 'group' as 'group' | 'copy' | 'direct',
  groups: [] as string[],
  copyFromUser: '',
  policies: [] as string[],
  tags: [{ key: '', value: '' }] as { key: string; value: string }[]
})
const creating = ref(false)
const permissionSearch = ref('')
const policyTypeFilter = ref('all')

// Fetch groups and policies for wizard
const { data: groupsData } = await useFetch('/api/iam/groups-full', { query: { pageSize: 100 } })
const { data: policiesData } = await useFetch('/api/iam/policies-full', { query: { pageSize: 100 } })

const filteredGroups = computed(() => {
  const items = groupsData.value?.items || []
  if (!permissionSearch.value) return items
  return items.filter((g: any) => g.name.toLowerCase().includes(permissionSearch.value.toLowerCase()))
})

const filteredPolicies = computed(() => {
  let items = policiesData.value?.items || []
  if (policyTypeFilter.value !== 'all') {
    items = items.filter((p: any) => policyTypeFilter.value === 'managed' ? p.type === 'Managed' : p.type === 'Custom')
  }
  if (!permissionSearch.value) return items
  return items.filter((p: any) => p.name.toLowerCase().includes(permissionSearch.value.toLowerCase()))
})

// Delete confirmation
const showDeleteConfirm = ref(false)
const deleteTarget = ref<{ id: string; username: string } | null>(null)
const deleteConfirmText = ref('')
const deleting = ref(false)

// Edit dialog
const showEditDialog = ref(false)
const editTarget = ref<any>(null)
const editForm = ref({ username: '', email: '' })
const saving = ref(false)

// Actions dropdown
const openActions = ref<string | null>(null)

function openCreateWizard() {
  createForm.value = {
    username: '', consoleAccess: false, passwordType: 'autogenerated', customPassword: '',
    requirePasswordChange: true, permissionMode: 'group', groups: [], copyFromUser: '',
    policies: [], tags: [{ key: '', value: '' }]
  }
  createStep.value = 1
  createSuccess.value = false
  showCreateWizard.value = true
}

function addTag() { createForm.value.tags.push({ key: '', value: '' }) }
function removeTag(i: number) { createForm.value.tags.splice(i, 1) }

function canProceedStep1() {
  if (!createForm.value.username.trim()) return false
  if (createForm.value.consoleAccess && createForm.value.passwordType === 'custom' && !createForm.value.customPassword) return false
  return true
}

async function submitCreate() {
  creating.value = true
  try {
    const res = await $fetch<any>('/api/iam/users-full', {
      method: 'POST',
      body: {
        username: createForm.value.username,
        consoleAccess: createForm.value.consoleAccess,
        passwordType: createForm.value.passwordType,
        groups: createForm.value.groups,
        policies: createForm.value.policies,
        tags: createForm.value.tags.filter(t => t.key)
      }
    })
    createdUsername.value = createForm.value.username
    createdUserId.value = res.id || 'u' + Date.now()
    createSuccess.value = true
  } finally {
    creating.value = false
  }
}

function downloadCsv() {
  const csv = `User Name,Password,Access Key,Console URL\n${createdUsername.value},${createForm.value.consoleAccess ? (createForm.value.passwordType === 'autogenerated' ? 'Auto-generated' : createForm.value.customPassword) : 'N/A'},N/A,https://console.example.com/`
  const blob = new Blob([csv], { type: 'text/csv' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = `${createdUsername.value}-credentials.csv`; a.click()
  URL.revokeObjectURL(url)
}

function confirmDelete(user: any) {
  deleteTarget.value = { id: user.id, username: user.username }
  deleteConfirmText.value = ''
  showDeleteConfirm.value = true
  openActions.value = null
}

async function doDelete() {
  if (!deleteTarget.value || deleteConfirmText.value !== deleteTarget.value.username) return
  deleting.value = true
  try {
    await $fetch(`/api/iam/users-full/${deleteTarget.value.id}`, { method: 'DELETE' })
    showDeleteConfirm.value = false
    deleteTarget.value = null
    await refresh()
  } finally { deleting.value = false }
}

function openEdit(user: any) {
  editTarget.value = user
  editForm.value = { username: user.username, email: user.email }
  showEditDialog.value = true
  openActions.value = null
}

async function doEdit() {
  if (!editTarget.value) return
  saving.value = true
  try {
    await $fetch(`/api/iam/users-full/${editTarget.value.id}`, { method: 'PUT', body: editForm.value })
    showEditDialog.value = false
    editTarget.value = null
    await refresh()
  } finally { saving.value = false }
}

function toggleActions(id: string) {
  openActions.value = openActions.value === id ? null : id
}

function relativeTime(dateStr: string) {
  if (!dateStr || dateStr === 'Never') return 'Never'
  const d = new Date(dateStr)
  const now = new Date()
  const diffMs = now.getTime() - d.getTime()
  const days = Math.floor(diffMs / 86400000)
  if (days === 0) return 'Today'
  if (days === 1) return 'Yesterday'
  if (days < 30) return `${days} days ago`
  if (days < 365) return `${Math.floor(days / 30)} months ago`
  return `${Math.floor(days / 365)} years ago`
}

function closeAll() {
  showColumnSelector.value = false
  openActions.value = null
}
</script>

<template>
  <div @click="closeAll">
    <!-- ============ LIST VIEW ============ -->
    <template v-if="!showCreateWizard">
      <div class="flex items-center justify-between mb-4">
        <h1 class="text-xl font-normal text-gray-900">IAM users</h1>
        <div class="flex gap-2">
          <button @click="refresh()" class="px-3 py-1.5 bg-white border border-gray-300 rounded text-sm text-gray-700 hover:bg-gray-50 flex items-center gap-1">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>
            Refresh
          </button>
          <button @click="openCreateWizard()" class="px-4 py-1.5 bg-[#ec7211] text-white rounded text-sm font-medium hover:bg-[#d6670e] flex items-center gap-1">
            Create user
          </button>
        </div>
      </div>

      <!-- Toolbar: search + column selector -->
      <div class="flex items-center gap-3 mb-3">
        <div class="relative flex-1 max-w-sm">
          <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
          <input v-model="search" type="text" placeholder="Filter users" class="w-full pl-9 pr-3 py-1.5 border border-gray-300 rounded text-sm focus:outline-none focus:ring-1 focus:ring-[#006ce0] focus:border-[#006ce0]" />
        </div>
        <div class="relative" @click.stop>
          <button @click="showColumnSelector = !showColumnSelector" class="p-2 bg-white border border-gray-300 rounded-md hover:bg-gray-50" title="Select columns">
            <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.066 2.573c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.573 1.066c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.066-2.573c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" /><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
          </button>
          <div v-if="showColumnSelector" class="absolute right-0 top-full mt-1 w-56 bg-white rounded-md shadow-lg border py-2 z-40">
            <div class="px-3 py-1 text-xs font-semibold text-gray-500 uppercase">Visible columns</div>
            <label v-for="col in columns" :key="col.key" class="flex items-center gap-2 px-3 py-1.5 hover:bg-gray-50 cursor-pointer">
              <input type="checkbox" v-model="col.visible" :disabled="col.required" class="text-blue-600 rounded" />
              <span class="text-sm text-gray-700">{{ col.label }}</span>
            </label>
          </div>
        </div>
      </div>

      <!-- Count + Table -->
      <p class="text-sm text-gray-600 mb-3">{{ data?.total || data?.items?.length || 0 }} users found</p>

      <div class="bg-white border border-gray-200 overflow-hidden">
        <table class="w-full">
          <thead>
            <tr class="bg-[#f2f3f3] border-b border-gray-300">
              <th class="w-10 px-3 py-2"><input type="checkbox" class="rounded text-[#006ce0]" /></th>
              <th v-for="col in visibleColumns" :key="col.key" class="text-left px-3 py-2 text-xs font-bold text-gray-600 whitespace-nowrap">
                {{ col.label }}
              </th>
              <th class="w-16 px-3 py-2"></th>
            </tr>
          </thead>
          <tbody v-if="data">
            <tr v-for="u in (data?.items || [])" :key="u.id" class="border-b border-gray-100 hover:bg-[#f1faff] transition-colors" style="height:48px;">
              <td class="px-3 py-3"><input type="checkbox" class="rounded" /></td>
              <!-- User name -->
              <td v-if="columns.find(c => c.key === 'username')?.visible" class="px-4 py-3">
                <NuxtLink :to="`/iam/users/${u.id}`" class="text-[#006ce0] hover:text-[#004ba0] hover:underline text-sm">{{ u.username }}</NuxtLink>
              </td>
              <!-- Groups -->
              <td v-if="columns.find(c => c.key === 'groups')?.visible" class="px-4 py-3 text-sm text-gray-700">
                {{ u.groups.join(', ') || '—' }}
              </td>
              <!-- Access key age -->
              <td v-if="columns.find(c => c.key === 'accessKeyAge')?.visible" class="px-4 py-3 text-sm">
                <span v-if="u.accessKeyAge > 0" :class="u.accessKeyAge > 90 ? 'text-orange-600 font-medium' : 'text-gray-700'">
                  {{ u.accessKeyAge }} days
                  <span v-if="u.accessKeyAge > 90" class="ml-1" title="Access key age exceeds 90 days">⚠</span>
                </span>
                <span v-else class="text-gray-400">N/A</span>
              </td>
              <!-- Password age -->
              <td v-if="columns.find(c => c.key === 'passwordAge')?.visible" class="px-4 py-3 text-sm">
                <span v-if="u.passwordEnabled" :class="u.passwordAge > 90 ? 'text-orange-600 font-medium' : 'text-gray-700'">
                  {{ u.passwordAge }} days
                  <span v-if="u.passwordAge > 90" class="ml-1" title="Password age exceeds 90 days">⚠</span>
                </span>
                <span v-else class="text-gray-400">N/A</span>
              </td>
              <!-- MFA -->
              <td v-if="columns.find(c => c.key === 'mfa')?.visible" class="px-4 py-3 text-sm">
                <span v-if="u.mfaEnabled" class="text-green-600">✅ Enabled</span>
                <span v-else class="text-red-500">❌ Disabled</span>
              </td>
              <!-- Last activity -->
              <td v-if="columns.find(c => c.key === 'lastActivity')?.visible" class="px-4 py-3 text-sm text-gray-600">
                {{ relativeTime(u.lastActivity) }}
              </td>
              <!-- Console last sign-in -->
              <td v-if="columns.find(c => c.key === 'consoleLastSignIn')?.visible" class="px-4 py-3 text-sm text-gray-600">
                {{ relativeTime(u.consoleLastSignIn) }}
              </td>
              <!-- Access key last used -->
              <td v-if="columns.find(c => c.key === 'accessKeyLastUsed')?.visible" class="px-4 py-3 text-sm text-gray-600">
                {{ relativeTime(u.accessKeyLastUsed) }}
              </td>
              <!-- Actions -->
              <td class="px-4 py-3">
                <div class="relative">
                  <button @click.stop="toggleActions(u.id)" class="p-1 rounded hover:bg-gray-200 text-gray-500">
                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z" /></svg>
                  </button>
                  <div v-if="openActions === u.id" class="absolute right-0 top-full mt-1 w-36 bg-white rounded-md shadow-lg border py-1 z-30">
                    <NuxtLink :to="`/iam/users/${u.id}`" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-50">View</NuxtLink>
                    <button @click="openEdit(u)" class="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-50">Edit</button>
                    <button @click="confirmDelete(u)" class="w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-red-50">Delete</button>
                  </div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
        <div v-if="data && (data?.items || []).length === 0" class="p-8 text-center text-sm text-gray-500">No users found</div>
      </div>

      <!-- Pagination -->
      <div v-if="data && (data?.total || 0) > pageSize" class="flex items-center justify-between mt-3 pt-3 border-t border-gray-200">
        <div class="flex items-center gap-1">
          <button :disabled="page <= 1" @click="page--" class="px-2 py-1 text-sm border border-gray-300 rounded bg-white text-gray-700 hover:bg-gray-50 disabled:opacity-40">‹</button>
          <template v-for="p in Math.ceil(((data?.total || 0) || 0) / pageSize)" :key="p">
            <button v-if="p <= 3 || p === Math.ceil(((data?.total || 0) || 0) / pageSize) || Math.abs(p - page) <= 1"
              @click="page = p"
              :class="['px-2.5 py-1 text-sm border rounded', p === page ? 'bg-[#006ce0] text-white border-[#006ce0]' : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-50']">
              {{ p }}
            </button>
            <span v-else-if="p === 4 || p === Math.ceil(((data?.total || 0) || 0) / pageSize) - 1" class="px-1 text-gray-400">…</span>
          </template>
          <button :disabled="page * pageSize >= (data?.total || 0)" @click="page++" class="px-2 py-1 text-sm border border-gray-300 rounded bg-white text-gray-700 hover:bg-gray-50 disabled:opacity-40">›</button>
        </div>
        <span class="text-sm text-gray-600">{{ (page - 1) * pageSize + 1 }}–{{ Math.min(page * pageSize, (data?.total || 0)) }} of {{ (data?.total || 0) }}</span>
      </div>
    </template>

    <!-- ============ CREATE USER WIZARD (full-page) ============ -->
    <template v-if="showCreateWizard">
      <div class="max-w-3xl mx-auto">
        <!-- Header -->
        <div class="flex items-center gap-3 mb-6">
          <button @click="showCreateWizard = false" class="text-gray-400 hover:text-gray-600">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
          </button>
          <h1 class="text-2xl font-bold text-gray-900">Create user</h1>
        </div>

        <!-- Step indicators -->
        <div v-if="!createSuccess" class="flex items-center gap-2 mb-8">
          <template v-for="s in 4" :key="s">
            <div :class="['flex items-center gap-2', s <= createStep ? 'text-blue-600' : 'text-gray-400']">
              <div :class="['w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold border-2', s < createStep ? 'bg-blue-600 border-blue-600 text-white' : s === createStep ? 'border-blue-600 text-blue-600' : 'border-gray-300 text-gray-400']">
                <svg v-if="s < createStep" class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" /></svg>
                <span v-else>{{ s }}</span>
              </div>
              <span class="text-sm font-medium hidden sm:inline">
                {{ ['User details', 'Set permissions', 'Add tags', 'Review and create'][s - 1] }}
              </span>
            </div>
            <div v-if="s < 4" :class="['flex-1 h-0.5 mx-2', s < createStep ? 'bg-blue-600' : 'bg-gray-200']" />
          </template>
        </div>

        <!-- Success state -->
        <div v-if="createSuccess" class="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
          <div class="text-center mb-6">
            <div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <svg class="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" /></svg>
            </div>
            <h2 class="text-xl font-bold text-gray-900">User {{ createdUsername }} has been created</h2>
            <p class="text-sm text-gray-500 mt-2">The user can now access cloud services based on the permissions you assigned.</p>
          </div>
          <div class="flex justify-center gap-3">
            <button @click="downloadCsv()" class="px-4 py-2 bg-white border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 flex items-center gap-2">
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
              Download .csv
            </button>
            <button class="px-4 py-2 bg-white border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50 flex items-center gap-2">
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
              Send email
            </button>
          </div>
          <div class="flex justify-center mt-6">
            <button @click="showCreateWizard = false; refresh()" class="px-6 py-2 bg-blue-600 text-white rounded-md text-sm font-medium hover:bg-blue-700">
              Return to users list
            </button>
          </div>
        </div>

        <!-- Wizard body -->
        <div v-else class="bg-white rounded-lg shadow-sm border border-gray-200">
          <!-- Step 1: User details -->
          <div v-if="createStep === 1" class="p-6">
            <h2 class="text-lg font-bold text-gray-900 mb-1">User details</h2>
            <p class="text-sm text-gray-500 mb-6">Step 1 of 4 — Specify user details</p>

            <div class="space-y-5">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">User name <span class="text-red-500">*</span></label>
                <input v-model="createForm.username" type="text" placeholder="Enter user name" class="w-full max-w-md px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" />
              </div>

              <label class="flex items-start gap-3 cursor-pointer">
                <input type="checkbox" v-model="createForm.consoleAccess" class="mt-1 rounded text-blue-600" />
                <div>
                  <span class="text-sm font-medium text-gray-900">Provide user access to the Console</span>
                  <p class="text-xs text-gray-500 mt-0.5">Creates a password for console sign-in</p>
                </div>
              </label>

              <div v-if="createForm.consoleAccess" class="ml-7 space-y-4 p-4 bg-gray-50 rounded-md border border-gray-200">
                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-2">Console password</label>
                  <div class="space-y-2">
                    <label class="flex items-center gap-2">
                      <input type="radio" v-model="createForm.passwordType" value="autogenerated" class="text-blue-600" />
                      <span class="text-sm text-gray-700">I want to create an IAM user</span>
                    </label>
                    <label class="flex items-center gap-2">
                      <input type="radio" v-model="createForm.passwordType" value="custom" class="text-blue-600" />
                      <span class="text-sm text-gray-700">Custom password</span>
                    </label>
                  </div>
                </div>

                <div v-if="createForm.passwordType === 'custom'">
                  <input v-model="createForm.customPassword" type="password" placeholder="Enter password" class="w-full max-w-sm px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                </div>

                <label class="flex items-center gap-2">
                  <input type="checkbox" v-model="createForm.requirePasswordChange" class="rounded text-blue-600" />
                  <span class="text-sm text-gray-700">User must create a new password at next sign-in</span>
                </label>
              </div>
            </div>
          </div>

          <!-- Step 2: Set permissions -->
          <div v-if="createStep === 2" class="p-6">
            <h2 class="text-lg font-bold text-gray-900 mb-1">Set permissions</h2>
            <p class="text-sm text-gray-500 mb-6">Step 2 of 4 — Choose how to grant permissions</p>

            <!-- Permission mode tabs -->
            <div class="flex border-b border-gray-200 mb-4">
              <button
                v-for="mode in [{ key: 'group', label: 'Add user to group' }, { key: 'copy', label: 'Copy permissions from existing user' }, { key: 'direct', label: 'Attach policies directly' }]"
                :key="mode.key"
                @click="createForm.permissionMode = mode.key as any; permissionSearch = ''"
                :class="['px-4 py-2.5 text-sm font-medium border-b-2 transition-colors -mb-px', createForm.permissionMode === mode.key ? 'border-blue-600 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700']"
              >
                {{ mode.label }}
              </button>
            </div>

            <!-- Search -->
            <div v-if="createForm.permissionMode !== 'copy'" class="mb-3">
              <input v-model="permissionSearch" type="text" :placeholder="createForm.permissionMode === 'group' ? 'Search groups...' : 'Search policies...'" class="w-full max-w-sm px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
            </div>

            <!-- Policy type filter -->
            <div v-if="createForm.permissionMode === 'direct'" class="flex gap-2 mb-3">
              <button v-for="f in [{ key: 'all', label: 'All' }, { key: 'managed', label: 'Managed' }, { key: 'customer', label: 'Custom' }]" :key="f.key"
                @click="policyTypeFilter = f.key"
                :class="['px-3 py-1 text-xs rounded-full border transition-colors', policyTypeFilter === f.key ? 'bg-blue-600 text-white border-blue-600' : 'bg-white text-gray-600 border-gray-300 hover:bg-gray-50']">
                {{ f.label }}
              </button>
            </div>

            <!-- Group list -->
            <div v-if="createForm.permissionMode === 'group'" class="max-h-60 overflow-y-auto border border-gray-200 rounded-md divide-y divide-gray-100">
              <label v-for="g in filteredGroups" :key="g.id" class="flex items-center gap-3 px-4 py-2.5 hover:bg-blue-50/50 cursor-pointer">
                <input type="checkbox" :value="g.name" v-model="createForm.groups" class="text-blue-600 rounded" />
                <div>
                  <span class="text-sm font-medium text-gray-900">{{ g.name }}</span>
                  <span class="text-xs text-gray-500 ml-2">{{ g.description }}</span>
                </div>
              </label>
              <p v-if="!filteredGroups.length" class="px-4 py-6 text-sm text-gray-400 text-center">No groups found</p>
            </div>

            <!-- Copy from user -->
            <div v-if="createForm.permissionMode === 'copy'" class="space-y-3">
              <p class="text-sm text-gray-600">Select a user to copy permissions from:</p>
              <select v-model="createForm.copyFromUser" class="w-full max-w-md px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500">
                <option value="">Select a user...</option>
                <option v-for="u in (data?.items || [])" :key="u.id" :value="u.username">{{ u.username }}</option>
              </select>
            </div>

            <!-- Direct policies -->
            <div v-if="createForm.permissionMode === 'direct'" class="max-h-60 overflow-y-auto border border-gray-200 rounded-md divide-y divide-gray-100">
              <label v-for="p in filteredPolicies" :key="p.id" class="flex items-center gap-3 px-4 py-2.5 hover:bg-blue-50/50 cursor-pointer">
                <input type="checkbox" :value="p.name" v-model="createForm.policies" class="text-blue-600 rounded" />
                <div class="flex-1 min-w-0">
                  <span class="text-sm font-medium text-gray-900">{{ p.name }}</span>
                  <div class="flex items-center gap-2 mt-0.5">
                    <span :class="['text-xs px-1.5 py-0.5 rounded', p.type === 'Managed' ? 'bg-blue-100 text-blue-700' : 'bg-gray-100 text-gray-600']">{{ p.type }}</span>
                    <span class="text-xs text-gray-400 truncate">{{ p.description }}</span>
                  </div>
                </div>
              </label>
              <p v-if="!filteredPolicies.length" class="px-4 py-6 text-sm text-gray-400 text-center">No policies found</p>
            </div>
          </div>

          <!-- Step 3: Add tags -->
          <div v-if="createStep === 3" class="p-6">
            <h2 class="text-lg font-bold text-gray-900 mb-1">Add tags</h2>
            <p class="text-sm text-gray-500 mb-6">Step 3 of 4 — Tags are key-value pairs that help you organize and track users (optional)</p>

            <div class="space-y-2">
              <div class="grid grid-cols-[1fr_1fr_40px] gap-2 mb-1">
                <span class="text-xs font-semibold text-gray-500 uppercase">Key</span>
                <span class="text-xs font-semibold text-gray-500 uppercase">Value</span>
                <span></span>
              </div>
              <div v-for="(tag, i) in createForm.tags" :key="i" class="grid grid-cols-[1fr_1fr_40px] gap-2 items-center">
                <input v-model="tag.key" type="text" placeholder="Key" class="px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                <input v-model="tag.value" type="text" placeholder="Value" class="px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
                <button @click="removeTag(i)" class="p-2 text-red-500 hover:text-red-700 hover:bg-red-50 rounded">
                  <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>
                </button>
              </div>
            </div>
            <button @click="addTag()" class="mt-3 text-sm text-blue-600 hover:text-blue-800 flex items-center gap-1">
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" /></svg>
              Add another tag
            </button>
          </div>

          <!-- Step 4: Review -->
          <div v-if="createStep === 4" class="p-6">
            <h2 class="text-lg font-bold text-gray-900 mb-1">Review and create</h2>
            <p class="text-sm text-gray-500 mb-6">Step 4 of 4 — Review the user details before creating</p>

            <div class="space-y-5">
              <!-- User details -->
              <div class="bg-gray-50 rounded-lg p-4">
                <h3 class="text-sm font-semibold text-gray-700 mb-3">User details</h3>
                <dl class="grid grid-cols-[140px_1fr] gap-y-2 text-sm">
                  <dt class="text-gray-500">User name</dt>
                  <dd class="text-gray-900 font-medium">{{ createForm.username }}</dd>
                  <dt class="text-gray-500">Console access</dt>
                  <dd class="text-gray-900">{{ createForm.consoleAccess ? 'Yes' : 'No' }}</dd>
                  <template v-if="createForm.consoleAccess">
                    <dt class="text-gray-500">Password type</dt>
                    <dd class="text-gray-900">{{ createForm.passwordType === 'autogenerated' ? 'Autogenerated' : 'Custom' }}</dd>
                  </template>
                </dl>
              </div>

              <!-- Permissions -->
              <div class="bg-gray-50 rounded-lg p-4">
                <h3 class="text-sm font-semibold text-gray-700 mb-3">Permissions</h3>
                <dl class="grid grid-cols-[140px_1fr] gap-y-2 text-sm">
                  <dt class="text-gray-500">Permission type</dt>
                  <dd class="text-gray-900">{{ { group: 'Group membership', copy: 'Copy from user', direct: 'Direct policies' }[createForm.permissionMode] }}</dd>
                  <template v-if="createForm.permissionMode === 'group'">
                    <dt class="text-gray-500">Groups</dt>
                    <dd class="text-gray-900">{{ createForm.groups.length ? createForm.groups.join(', ') : 'None' }}</dd>
                  </template>
                  <template v-if="createForm.permissionMode === 'copy'">
                    <dt class="text-gray-500">Copy from</dt>
                    <dd class="text-gray-900">{{ createForm.copyFromUser || 'None' }}</dd>
                  </template>
                  <template v-if="createForm.permissionMode === 'direct'">
                    <dt class="text-gray-500">Policies</dt>
                    <dd class="text-gray-900">{{ createForm.policies.length ? createForm.policies.join(', ') : 'None' }}</dd>
                  </template>
                </dl>
              </div>

              <!-- Tags -->
              <div class="bg-gray-50 rounded-lg p-4">
                <h3 class="text-sm font-semibold text-gray-700 mb-3">Tags</h3>
                <div v-if="createForm.tags.filter(t => t.key).length">
                  <div v-for="tag in createForm.tags.filter(t => t.key)" :key="tag.key" class="flex gap-2 text-sm mb-1">
                    <span class="font-medium text-gray-700">{{ tag.key }}:</span>
                    <span class="text-gray-600">{{ tag.value }}</span>
                  </div>
                </div>
                <p v-else class="text-sm text-gray-400">No tags</p>
              </div>
            </div>
          </div>

          <!-- Wizard footer -->
          <div class="px-6 py-4 border-t border-gray-200 flex items-center justify-between">
            <button v-if="createStep > 1" @click="createStep--" class="px-4 py-2 text-sm text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50">
              Previous
            </button>
            <div v-else />
            <div class="flex gap-2">
              <button @click="showCreateWizard = false" class="px-4 py-2 text-sm text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50">Cancel</button>
              <button v-if="createStep < 4" @click="createStep++" :disabled="createStep === 1 && !canProceedStep1()" class="px-4 py-2 text-sm text-white bg-blue-600 rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed">
                Next
              </button>
              <button v-else @click="submitCreate()" :disabled="creating" class="px-6 py-2 text-sm text-white bg-blue-600 rounded-md hover:bg-blue-700 disabled:opacity-50">
                {{ creating ? 'Creating...' : 'Create user' }}
              </button>
            </div>
          </div>
        </div>
      </div>
    </template>

    <!-- ============ EDIT DIALOG ============ -->
    <div v-if="showEditDialog" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" @click.self="showEditDialog = false">
      <div class="bg-white rounded-lg shadow-xl w-full max-w-md">
        <div class="px-6 py-4 border-b border-gray-200">
          <h2 class="text-lg font-semibold text-gray-900">Edit user</h2>
        </div>
        <div class="px-6 py-5 space-y-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Username</label>
            <input v-model="editForm.username" type="text" class="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Email</label>
            <input v-model="editForm.email" type="text" class="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-blue-500" />
          </div>
        </div>
        <div class="px-6 py-4 border-t border-gray-200 flex justify-end gap-2">
          <button @click="showEditDialog = false" class="px-4 py-2 text-sm text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50">Cancel</button>
          <button @click="doEdit()" :disabled="saving" class="px-4 py-2 text-sm text-white bg-blue-600 rounded-md hover:bg-blue-700 disabled:opacity-50">
            {{ saving ? 'Saving...' : 'Save changes' }}
          </button>
        </div>
      </div>
    </div>

    <!-- ============ DELETE CONFIRM (type username to confirm) ============ -->
    <div v-if="showDeleteConfirm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" @click.self="showDeleteConfirm = false">
      <div class="bg-white rounded-lg shadow-xl w-full max-w-md">
        <div class="px-6 py-4 border-b border-gray-200">
          <h2 class="text-lg font-semibold text-gray-900">Delete user</h2>
        </div>
        <div class="px-6 py-5 space-y-3">
          <p class="text-sm text-gray-700">Are you sure you want to delete user <strong>{{ deleteTarget?.username }}</strong>?</p>
          <p class="text-sm text-gray-500">This action cannot be undone. All access keys and policies associated with this user will be removed.</p>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Type <strong>{{ deleteTarget?.username }}</strong> to confirm deletion:</label>
            <input v-model="deleteConfirmText" type="text" :placeholder="deleteTarget?.username" class="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-red-500" />
          </div>
        </div>
        <div class="px-6 py-4 border-t border-gray-200 flex justify-end gap-2">
          <button @click="showDeleteConfirm = false" class="px-4 py-2 text-sm text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50">Cancel</button>
          <button @click="doDelete()" :disabled="deleting || deleteConfirmText !== deleteTarget?.username" class="px-4 py-2 text-sm text-white bg-red-600 rounded-md hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed">
            {{ deleting ? 'Deleting...' : 'Delete user' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>